using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Misars.Foundation.App.Patients
{
    public class PatientManager : PatientManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PatientManager(IPatientRepository patientRepository)
            : base(patientRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}