using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Misars.Foundation.App.Permissions;
using Misars.Foundation.App.Doctors;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Misars.Foundation.App.Shared;

namespace Misars.Foundation.App.Doctors
{
    public class DoctorsAppService : DoctorsAppServiceBase, IDoctorsAppService
    {
        //<suite-custom-code-autogenerated>
        public DoctorsAppService(IDoctorRepository doctorRepository, DoctorManager doctorManager, IDistributedCache<DoctorDownloadTokenCacheItem, string> downloadTokenCache)
            : base(doctorRepository, doctorManager, downloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}