using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Misars.Foundation.App.SurgeryTimetables
{
    public class SurgeryTimetableManager : SurgeryTimetableManagerBase
    {
        //<suite-custom-code-autogenerated>
        public SurgeryTimetableManager(ISurgeryTimetableRepository surgeryTimetableRepository)
            : base(surgeryTimetableRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}