using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Misars.Foundation.App.Filemanagements
{
    public class Filemanagement : FilemanagementBase
    {
        //<suite-custom-code-autogenerated>
        protected Filemanagement()
        {

        }

        public Filemanagement(Guid id, DateTime uploadDate, string? fileName = null, string? filePath = null)
            : base(id, uploadDate, fileName, filePath)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}