using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Misars.Foundation.App.Filemanagements
{
    public class FilemanagementManager : FilemanagementManagerBase
    {
        //<suite-custom-code-autogenerated>
        public FilemanagementManager(IFilemanagementRepository filemanagementRepository)
            : base(filemanagementRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}