using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Misars.Foundation.App.Doctors
{
    public class Doctor : DoctorBase
    {
        //<suite-custom-code-autogenerated>
        protected Doctor()
        {

        }

        public Doctor(Guid id, string? name = null, string? doctorID = null, string? specialty = null, string? department = null)
            : base(id, name, doctorID, specialty, department)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}