using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Misars.Foundation.App.Doctors
{
    public class DoctorManager : DoctorManagerBase
    {
        //<suite-custom-code-autogenerated>
        public DoctorManager(IDoctorRepository doctorRepository)
            : base(doctorRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}