using Misars.Foundation.App.Shared;
using Misars.Foundation.App.Patients;
using Misars.Foundation.App.Doctors;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Misars.Foundation.App.Permissions;
using Misars.Foundation.App.SurgeryTimetables;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Misars.Foundation.App.Shared;

namespace Misars.Foundation.App.SurgeryTimetables
{
    public class SurgeryTimetablesAppService : SurgeryTimetablesAppServiceBase, ISurgeryTimetablesAppService
    {
        //<suite-custom-code-autogenerated>
        public SurgeryTimetablesAppService(ISurgeryTimetableRepository surgeryTimetableRepository, SurgeryTimetableManager surgeryTimetableManager, IDistributedCache<SurgeryTimetableDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Misars.Foundation.App.Doctors.Doctor, Guid> doctorRepository, IRepository<Misars.Foundation.App.Patients.Patient, Guid> patientRepository)
            : base(surgeryTimetableRepository, surgeryTimetableManager, downloadTokenCache, doctorRepository, patientRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}